spring:
  application:
    name: portai
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

server:
  port: 8080

logging:
  level:
    com.portai: debug
    org.hibernate.SQL: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
